DROP TABLE IF EXISTS "public"."t_simple";
CREATE TABLE "public"."t_simple"
(
    "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE  1
        MAXVALUE 9223372036854775807
        START 1
        CACHE 1),
    name  varchar(64) COLLATE "pg_catalog"."default" NULL,
    age   int2 ,
    delete_flag int2(1) ,
    deleted int2(1),
    version     int4,
    create_time timestamptz ,
    update_time timestamptz,
    primary key (id)
);
COMMENT ON COLUMN "public"."t_simple"."id" IS '主键';
COMMENT ON COLUMN "public"."t_simple"."name" IS '名字';

ALTER TABLE "public"."t_simple" ADD CONSTRAINT "pk_t_simple" PRIMARY KEY ("id");